import { createContext } from "react";

export const DataContext = createContext({
	dob: "",
	phone: "",
	email: "",
	address: "",
	profile: "",
	residence: "",
	last_name: "",
	full_name: "",
	first_name: "",
	status: "",
	me_sub_heading: "",
	me_description: "",
	aboutMe_sub_heading: "",
	aboutMe_description: "",
	skills_sub_heading: "",
	experience_sub_heading: "",
	education_sub_heading: "",
	contact_sub_heading: "",
	signature: "",
	freelance: false,
	socials: [],
	experiences: [],
	education: [],
	skills: [],
	tools: [],
});
